require(tidyverse)
require(Hmisc)
require(ggrepel)
president_primary_polls <- read.csv("polls/president_primary_polls.csv")
president_polls <- read.csv("polls/president_polls.csv")
pollster_ratings <- read.csv("pollster-ratings/pollster-ratings.csv")
media_online <- read.csv("media-mentions-2020/online_weekly.csv")
media_cable <- read.csv("media-mentions-2020/cable_weekly.csv")
president_polls <- add_ratings_weights(president_polls)
president_primary_polls <- add_ratings_weights(president_primary_polls)
president_polls$candidate_name <- clean_candidate_name(president_polls$candidate_name)
president_primary_polls$candidate_name <- clean_candidate_name(president_primary_polls$candidate_name)
media_online$name <- clean_candidate_name(media_online$name)
media_cable$name <- clean_candidate_name(media_cable$name)
president_polls$Month <- month_column_add(president_polls$end_date)
president_primary_polls$Month <- month_column_add(president_primary_polls$end_date)
media_online$Month <- month_column_add(media_online$date)
media_cable$Month <- month_column_add(media_cable$date)
