require(tidyverse)
require(Hmisc)
require(ggrepel)
president_primary_polls <- read.csv("polls/president_primary_polls.csv")
president_polls <- read.csv("polls/president_polls.csv")
pollster_ratings <- read.csv("pollster-ratings/pollster-ratings.csv")
media_online <- read.csv("media-mentions-2020/online_weekly.csv")
media_cable <- read.csv("media-mentions-2020/cable_weekly.csv")
president_polls <- add_ratings_weights(president_polls)
president_primary_polls <- add_ratings_weights(president_primary_polls)
president_polls$candidate_name <- clean_candidate_name(president_polls$candidate_name)
president_primary_polls$candidate_name <- clean_candidate_name(president_primary_polls$candidate_name)
media_online$name <- clean_candidate_name(media_online$name)
media_cable$name <- clean_candidate_name(media_cable$name)
president_polls$Month <- month_column_add(president_polls$end_date)
president_primary_polls$Month <- month_column_add(president_primary_polls$end_date)
media_online$Month <- month_column_add(media_online$date)
media_cable$Month <- month_column_add(media_cable$date)
president_polls$start_date <- parse_date(as.character(president_polls$start_date),format = "%m/%d/%y")
president_primary_polls$start_date <- parse_date(as.character(president_primary_polls$start_date),format = "%m/%d/%y")
president_polls$end_date <- parse_date(as.character(president_polls$end_date),format = "%m/%d/%y")
president_primary_polls$end_date <- parse_date(as.character(president_primary_polls$end_date),format = "%m/%d/%y")
media_online$date <- parse_date(as.character(media_online$date,"%Y-%m-%d"))
media_cable$date <- parse_date(as.character(media_cable$date,"%Y-%m-%d"))
media_total <- inner_join(media_cable,media_online,by = c("date","name","Month"))
media_total$combined <- media_total$matched_stories + media_total$matched_clips
sum_by_date <- media_total %>% group_by(date) %>% summarise(total_mentions = sum(matched_clips)+sum(matched_stories))
media_total_joined <- left_join(media_total,sum_by_date)
media_total_joined$Coverage_share <- 100*media_total_joined$combined / media_total_joined$total_mentions
